name: retrofit_example
description: Retrofit generator
version: 0.0.1
author: Trevor Wang <trevor.wang@qq.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  retrofit:

dev_dependencies:
  retrofit_generator:
  build_runner:

dependency_overrides:
  retrofit:
    path: ../annotation
  retrofit_generator:
    path: ../generator
