name: retrofit_example
description: Retrofit generator
version: 0.0.1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  retrofit:
  json_annotation:
  logger: ^1.0.0
  dio: ^4.0.0

dev_dependencies:
  test: ^1.17.10
  retrofit_generator:
  build_runner: ^2.0.1
  json_serializable: ^6.1.1
  mock_web_server: ^5.0.0-nullsafety.1

dependency_overrides:
  retrofit:
    path: ../retrofit
  retrofit_generator:
    path: ../generator
  source_gen: ^1.0.0
