name: retrofit_example
description: Retrofit generator
version: 0.0.1
author: Trevor Wang <trevor.wang@qq.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  retrofit:
  json_annotation:
  logger:

dev_dependencies:
  test:
  retrofit_generator:
  build_runner: ^1.4.0
  json_serializable: any
  mock_web_server:

dependency_overrides:
  retrofit:
    path: ../annotation
  retrofit_generator:
    path: ../generator
