name: retrofit_example
description: Retrofit generator
version: 2.0.0-dev
author: Trevor Wang <trevor.wang@qq.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  retrofit:
  json_annotation:
  logger:
  dart_json_mapper:
  reflectable: ^2.2.4

dev_dependencies:
  test:
  retrofit_generator:
  build_runner: ^1.4.0
  json_serializable: any
  mock_web_server:

dependency_overrides:
  retrofit:
    path: ../annotation
  retrofit_generator:
    path: ../generator
