name: retrofit_example
description: Retrofit generator
version: 0.0.1
author: Trevor Wang <trevor.wang@qq.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  retrofit:
  json_annotation:
  logger:

dev_dependencies:
  retrofit_generator:
  build_runner: 1.4.0
  json_serializable: any

dependency_overrides:
  retrofit:
    path: ../annotation
  retrofit_generator:
    path: ../generator
