name: retrofit_generator
description: retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
version: 2.0.0-beta2

homepage: https://mings.in/retrofit.dart/
repository: https://github.com/trevorwang/retrofit.dart/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0-prev3
  source_gen: ^1.0.0
  built_collection: ^5.0.0
  code_builder: ^3.7.0
  tuple: ^2.0.0
  retrofit: ^2.0.0-beta1
  analyzer: ^1.2.0
  dart_style: ^2.0.0
  build: ^2.0.0

dev_dependencies:
  test: 1.16.5
  source_gen_test: ^1.0.0

#dependency_overrides:
#   retrofit:
#     path: ../annotation