name: retrofit_generator
description: retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
version: 2.0.0+2

homepage: https://mings.in/retrofit.dart/
repository: https://github.com/trevorwang/retrofit.dart/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  source_gen: ^1.0.1
  built_collection: ^5.0.0
  code_builder: ^4.0.0
  tuple: ^2.0.0
  retrofit: ^2.0.0
  analyzer: ^1.7.0
  dart_style: ^2.0.1
  build: ^2.0.1

dev_dependencies:
  test: 1.17.4
  source_gen_test: ^1.0.0
