name: retrofit_generator
description: retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
version: 4.0.1

homepage: https://mings.in/retrofit.dart/
repository: https://github.com/trevorwang/retrofit.dart/

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dio: ^4.0.1
  source_gen: ^1.0.1
  built_collection: ^5.0.0
  code_builder: ^4.0.0
  tuple: ^2.0.0
  retrofit: ^3.0.1
  analyzer: '>=3.0.0 <5.0.0'
  dart_style: ^2.0.1
  build: ^2.0.1

dev_dependencies:
  test: ^1.17.10
  source_gen_test: ^1.0.0
