name: retrofit
version: 2.0.0-beta1

homepage: https://mings.in/retrofit.dart/
repository: https://github.com/trevorwang/retrofit.dart/
description: retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0-beta4
  meta: ^1.3.0
