name: retrofit
version: 4.0.1

homepage: https://mings.in/retrofit.dart/
repository: https://github.com/trevorwang/retrofit.dart/
description: retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: ^5.0.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
