name: retrofit
description: retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.
homepage: https://mings.in/retrofit.dart/
repository: https://github.com/trevorwang/retrofit.dart/
topics:
  - api
  - http
  - rest
  - dio
  - retrofit
version: 4.9.0
environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  dio: ^5.8.0
  meta: ^1.16.0

dev_dependencies:
  lints: any
  coverage: any
  test: any
